apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mr-dj-prod
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
spec:
  ingressClassName: traefik
  rules:
    - host: mr-dj.sevensa.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mr-dj-frontend
                port:
                  number: 80
  tls:
    - secretName: mr-dj-tls
      hosts:
        - mr-dj.sevensa.nl
